avocado/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('main.urls')),
    url(r'^secret-admin-url-shhh/', admin.site.urls),
]

main/urls.py
from django.conf.urls import url
from django.contrib import admin

from . import views

admin.site.site_header = 'Avocado Jobs administration'
app_name = 'main'
urlpatterns = [
    # /
    url(r'^$', views.index, name='index'),

    # /login/
    url(r'^login/$', views.get_login, name='login'),

    # /auth/
    url(r'^auth/$', views.token_post, name='auth'),

    # /logout/
    url(r'^logout/$', views.get_logout, name='logout'),

    # /about/
    url(r'^about/$', views.about, name='about'),

    # /about/
    url(r'^blog/$', views.blog, name='blog'),

    # /feedback/
    url(r'^feedback/$', views.feedback, name='feedback'),

    # /applications/
    url(r'^applications/$', views.applications, name='applications'),

    # /applications/<application_id>/
    url(r'^applications/(?P<application_id>[^/]*)/$', views.applications_delete, name='applications_delete'),

    # /reminders/
    url(r'^reminders/$', views.reminders, name='reminders'),

    # /reminders/<reminder_id>/
    url(r'^reminders/(?P<reminder_id>[^/]*)/$', views.reminders_delete, name='reminders_delete'),

    # /board/
    url(r'^board/$', views.board, name='board'),

    # /board/add/
    url(r'^board/add/$', views.board_add, name='board_add'),

    # /board/payment/<listing_id>
    url(r'^board/payment/(?P<listing_id>[^/]*)/$', views.board_payment, name='board_payment'),

    # /board/track/<listing_id>
    url(r'^board/track/(?P<listing_id>[^/]*)/$', views.board_track, name='board_track'),
]

main/models.py
import shortuuid
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


def generate_uuid():
    return shortuuid.ShortUUID('abdcefghkmnpqrstuvwxyzABDCEFGHKMNPQRSTUVWXYZ23456789').random(length=12)


class Application(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date_applied = models.DateField(default=timezone.now, null=True, blank=True)
    role = models.CharField(max_length=200)
    company = models.CharField(max_length=200)
    link = models.CharField(max_length=500, null=True, blank=True)
    salary = models.CharField(max_length=100, null=True, blank=True)
    notes = models.TextField(null=True, blank=True)

    TODO = 'todo'
    INITIAL = 'initial'
    NEED = 'need'
    AWAIT = 'await'
    SCHEDULED = 'scheduled'
    OFFER = 'offer'
    DECLINED = 'declined'
    REJECTED = 'rejected'
    STAGE_CHOICES = (
        (TODO, 'To Do'),
        (INITIAL, 'No initial response yet'),
        (NEED, 'I need to respond'),
        (AWAIT, 'Awaiting response'),
        (SCHEDULED, 'Interview scheduled'),
        (OFFER, 'Got offer'),
        (DECLINED, 'Declined'),
        (REJECTED, 'Got Rejected'),
    )
    stage = models.CharField(
        choices=STAGE_CHOICES,
        max_length=50,
    )

    def __str__(self):
        return self.user.email + ' - ' + self.role


class Reminder(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date_created = models.DateField(default=timezone.now)
    date_activation = models.DateTimeField()
    subject = models.CharField(max_length=400)
    body = models.TextField(null=True, blank=True)
    in_progress = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username + ': ' + self.subject


class Analytic(models.Model):
    created_at = models.DateTimeField(default=timezone.now)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    ip = models.GenericIPAddressField(null=True, blank=True)
    path = models.CharField(max_length=400, null=True, blank=True)
    querystring = models.CharField(max_length=400, null=True, blank=True)

    def __str__(self):
        return self.ip


class Listing(models.Model):
    id = models.CharField(
        max_length=50,
        primary_key=True,
        default=generate_uuid,
        editable=False,
    )
    created_at = models.DateTimeField(default=timezone.now)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    role_title = models.CharField(max_length=50)
    company_name = models.CharField(max_length=50)
    company_url = models.URLField()
    location = models.CharField(max_length=40)
    salary = models.CharField(max_length=40, null=True, blank=True)
    application_link = models.CharField(max_length=200)
    transaction_hash = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return self.role_title + ' at ' + self.company_name


class Tag(models.Model):
    value = models.CharField(max_length=50)
    listing = models.ForeignKey(
        Listing,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.value


class Address(models.Model):
    value = models.CharField(max_length=100)
    description = models.CharField(max_length=400, blank=True, null=True)
    last_used = models.DateTimeField()

    def __str__(self):
        return self.value

main/forms.py
from django import forms

from .models import Listing


class EmailForm(forms.Form):
    """The email form for the login page."""
    email = forms.EmailField(label="Your email address")


class ListingForm(forms.ModelForm):
    tags = forms.CharField(
        max_length=150,
        required=False,
    )

    class Meta:
        model = Listing
        fields = ['role_title', 'company_name', 'company_url', 'location', 'salary', 'application_link']

main/views.py
import base64
import json
import sys
import threading
import time

import analytics
import pytz
from dateutil.parser import parse
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.core.exceptions import ValidationError
from django.core.mail import send_mail
from django.core.signing import Signer
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.utils import timezone

from avocado import settings

from .address_ring import get_address, get_payment
from .forms import EmailForm, ListingForm
from .helpers import get_client_ip, log_analytic
from .models import Application, Listing, Reminder, Tag


def index(request):
    analytics.page(get_client_ip(request), 'Non Authed', 'Index', {
        'url': request.get_full_path(),
    })
    log_analytic(request)
    return render(request, 'main/index.html')


@login_required
def applications(request):
    if request.method == 'POST':
        body = request.body.decode('utf-8')
        data = json.loads(body)
        if 'role' not in data or 'company' not in data:
            return JsonResponse(status=400, data={
                'status': 'false',
                'message': 'Bad Request',
            })
        new_application = Application.objects.create(
            user=request.user,
            role=data['role'],
            company=data['company'],
        )
        if 'salary' in data:
            new_application.salary = data['salary']
        if 'date' in data:
            new_application.date_applied = data['date']
        if 'link' in data:
            new_application.link = data['link']
        if 'stage' in data:
            new_application.stage = data['stage']
        try:
            new_application.save()
        except:
            return JsonResponse(status=400, data={
                'status': 'false',
                'message': 'Bad Request. Invalid data.',
            })
        return JsonResponse({})
    elif request.method == 'PATCH':
        body = request.body.decode('utf-8')
        try:
            data = json.loads(body)
        except ValueError:
            return JsonResponse(status=400, data={
                'status': 'false',
                'message': 'Bad Request. Invalid JSON.',
            })

        if 'id' not in data:
            return JsonResponse(status=400, data={
                'status': 'false',
                'message': 'Bad Request. No id defined.',
            })

        applicationId = int(data['id'])

        newValues = {}
        if 'role' in data:
            newValues['role'] = data['role']
        if 'company' in data:
            newValues['company'] = data['company']
        if 'date' in data:
            newValues['date_applied'] = data['date']
        if 'link' in data:
            newValues['link'] = data['link']
        if 'salary' in data:
            newValues['salary'] = data['salary']
        if 'notes' in data:
            newValues['notes'] = data['notes']
        if 'stage' in data:
            newValues['stage'] = data['stage'].lower()

        if Application.objects.get(id=applicationId).user != request.user:
            return JsonResponse(status=401, data={
                'status': 'false',
                'message': 'Unauthorized',
            })

        Application.objects.filter(user=request.user, id=applicationId).update(**newValues)
        return JsonResponse({})
    elif request.method == 'GET':
        applications = Application.objects.filter(user=request.user).order_by('-date_applied', '-id').values('id', 'role', 'company', 'link', 'stage', 'salary', 'notes', 'date_applied')
        applications_list = list(applications)
        for item in applications_list:
            item['date'] = item.pop('date_applied')
        return JsonResponse(applications_list, safe=False)
    else:
        return redirect('main:index')


@login_required
def applications_delete(request, application_id):
    if request.method == 'DELETE':
        application = Application.objects.get(id=application_id)
        if application.user != request.user:
            return JsonResponse(status=401, data={
                'status': 'false',
                'message': 'Unauthorized',
            })
        else:
            application.delete()
            return JsonResponse({})
    else:
        return HttpResponse(status=404)


@login_required
def reminders(request):
    if request.method == 'POST':
        body = request.body.decode('utf-8')
        try:
            data = json.loads(body)
        except ValueError:
            return JsonResponse(status=400, data={
                'status': 'false',
                'message': 'Bad Request. Invalid JSON.',
            })
        required_fields = ['subject', 'body', 'day', 'hour']
        for field in required_fields:
            if field not in data:
                return JsonResponse(status=400, data={
                    'status': 'false',
                    'message': 'Bad Request. Missing fields.',
                })

        # normalize hour in case of only hour without minutes
        if len(data['hour']) == 1 or len(data['hour']) == 2:
            data['hour'] += ':00'

        try:
            new_reminder = Reminder.objects.create(
                user=request.user,
                subject=data['subject'],
                body=data['body'],
                date_activation=parse(data['day'] + ' ' + data['hour']),
            )
        except ValidationError:
            return JsonResponse(status=400, data={
                'status': 'false',
                'message': 'Bad Request. Invalid data.',
            })

        return JsonResponse({})
    elif request.method == 'GET':
        reminders = Reminder.objects.filter(user=request.user).order_by('date_activation').values('id', 'subject', 'body', 'date_activation')
        reminders_list = list(reminders)
        for rem in reminders_list:
            rem['date'] = rem.pop('date_activation').strftime('%Y-%m-%d %H:%M')
        return JsonResponse(reminders_list, safe=False)
    else:
        return redirect('main:index')


@login_required
def reminders_delete(request, reminder_id):
    if request.method == 'DELETE':
        reminder = Reminder.objects.get(id=reminder_id)
        if reminder.user != request.user:
            return JsonResponse(status=401, data={
                'status': 'false',
                'message': 'Unauthorized',
            })
        else:
            reminder.delete()
            return JsonResponse({})
    else:
        return HttpResponse(status=404)


def get_login(request):
    log_analytic(request)
    if request.user.is_authenticated:
        return redirect('main:index')
    return render(request, 'main/login.html', {
        'next': request.GET.get('next'),
    })


def token_post(request):
    if request.user.is_authenticated:
        messages.error(request, 'You are already logged in.')
        return redirect(settings.LOGIN_REDIRECT_URL)

    if request.GET.get('d'):
        # The user has clicked a login link.
        user = authenticate(token=request.GET['d'])
        if user is not None:
            login(request, user)
            # messages.success(request, 'Login successful.')
            return redirect(settings.LOGIN_REDIRECT_URL)
        else:
            messages.error(request, 'The login link was invalid or has expired. Please try to log in again.')
    elif request.method == 'POST':
        # The user has submitted the email form.
        form = EmailForm(request.POST)
        if form.is_valid():
            email_login_link(request, form.cleaned_data['email'])
            messages.success(request, 'Login email sent! Please check your inbox and click on the link.')
        else:
            messages.error(request, 'The email address was invalid. Please check the address and try again.')
    else:
        messages.error(request, 'The login link was invalid or has expired. Please try to log in again.')

    return redirect(settings.LOGIN_URL)


def email_login_link(request, email):
    current_site = get_current_site(request)

    # Create the signed structure containing the time and email address.
    email = email.lower().strip()
    data = {
        't': int(time.time()),
        'e': email,
    }
    data = Signer().sign(base64.b64encode(json.dumps(data).encode('utf8')).decode('utf8'))

    # Send the link by email.
    send_mail(
        'Login link for Avocado Jobs',
        render_to_string('main/token_auth_email.txt', {'current_site': current_site, 'data': data}, request=request),
        settings.DEFAULT_FROM_EMAIL,
        [email],
    )


@login_required
def get_logout(request):
    log_analytic(request)
    logout(request)
    return redirect(settings.LOGOUT_REDIRECT_URL)


@login_required
def feedback(request):
    if request.method == 'POST':
        body = request.body.decode('utf-8')
        data = json.loads(body)
        subject = 'Avocado Feedback from ' + request.user.email
        send_mail(
            subject,
            data['message'],
            settings.DEFAULT_FROM_EMAIL,
            [settings.EMAIL_ALERT],
        )
        return JsonResponse({})
    else:
        return redirect('main:index')


def about(request):
    log_analytic(request)
    return render(request, 'main/about.html')


def blog(request):
    log_analytic(request)
    return redirect('https://medium.com/avocado-jobs')


def board(request):
    log_analytic(request)
    listings = Listing.objects.filter(transaction_hash__isnull=False).order_by('-created_at')
    if request.GET.get('posting') == 'success':
        messages.success(request, 'Your posting is live! 🎊')
        return redirect('main:board')
    return render(request, 'main/board.html', {

main/templates/main/about.html
{% extends 'main/layout.html' %}

{% block content %}
    <div class="header">
        <div class="header-copy">
            <h1>About</h1>
        </div>
    </div>

    <div class="about">
        <strong>Summary</strong>
        <p>
            Avocado Jobs is a simple tool made exclusively for software people.
        </p>
        <p>
            Neither hiring nor choosing a company are easy tasks for software companies
            and software engineers respectively. It is common for candidates to apply
            to over 100 roles, thus keeping track of all this information is mandatory
            for sanity maintenance. Avocado Jobs does exactly that; it enables you to
            keep track of all the roles you have applied as a job seeking individual.
            Furthermore, it provides you with extra functionality to aid in the data
            manipulation.
        </p>

        <br>

        <strong>Privacy statement</strong>
        <p>
            Data that is provided to Avocado Jobs by its users is transported exclusively
            via HTTPS using strong encryption. The server of avocadojobs.com is located
            in New Jersey, US and the database is backed up on a daily basis in Oregon, US.
            Users' data will never be sold, donated, or become accessible by any third
            parties. Finally, Avocado Jobs does not track its users across the web.
        </p>

        <br>

        <strong>Team</strong>
        <p>
            Avocado Jobs is developed by
            <a href="https://sirodoht.xyz/" target="_blank" rel="noopener noreferrer">@sirodoht</a>.
        </p>
    </div>
{% endblock %}

main/templates/main/board.html
{% extends 'main/layout.html' %}

{% load static %}

{% block title %}Avocado Job Board | Job postings for the cryptoliterate companies{% endblock %}

{% block content %}
    <div class="header extended">
        <div class="header-copy extended">
            <h1>Find your next software <span>job</span> position</h1>
        </div>
    </div>

    <div class="board">
        <div class="board-header" id="board-header-track">
            {% if messages %}
                {% for message in messages %}
                    {{ message }}
                    <br>
                {% endfor %}
            {% else %}
                Tip: Click on the avocado on the left of each job to track it on your applications
            {% endif %}
        </div>

        {% csrf_token %}

        {% for item in listings %}
            <div class="board-item">
                <div class="board-item-content">
                    <div class="board-item-content-title">
                        <div class="board-item-content-title-icon">
                            <img src="{% static '/main/images/avocado-icon.svg' %}" alt="avocado icon" width="30" id="track-{{ item.id }}">
                        </div>
                        <div class="board-item-content-title-body">
                            <strong>{{ item.role_title }}</strong> at <a href="{{ item.company_url }}" target="_blank">{{ item.company_name }}</a>
                        </div>
                    </div>
                    <div class="board-item-content-text">
                        <div class="board-item-content-text-meta">
                            <div class="board-item-content-text-meta-location">{{ item.location }}</div>
                            {% if item.salary %}
                                <div class="board-item-content-text-meta-salary">Salary: {{ item.salary }}</div>
                            {% endif %}
                        </div>
                        <div class="board-item-content-text-meta">
                            <div class="board-item-content-text-meta-tags">
                                {% for tag in item.tag_set.all %}
                                    <div class="board-item-content-text-meta-tags-single">#{{ tag }}</div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="board-item-cta">
                    <a href="{% if '@' in item.application_link %} mailto:{{ item.application_link }} {% else %} {{ item.application_link }} {% endif %}" class="board-item-cta-btn" target="_blank">
                        Apply&nbsp;
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" width="15">
                            <path d="M16 11v6a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h6M13 1h6v6M8 12L19 1" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"/>
                        </svg>
                    </a>
                </div>
            </div>
        {% endfor %}
    </div>

    <input type='hidden' name='user_authenticated' value='{{ request.user.is_authenticated }}'>

    <script src="{% static '/main/scripts/axios.min.js' %}"></script>
    <script>
        function getUserAuth() {
            var inputElems = document.querySelectorAll('input');
            var userAuth = false;
            var i = 0;
            for (i = 0; i < inputElems.length; i++) {
                if (inputElems[i].name === 'user_authenticated') {
                    if (inputElems[i].value === 'True') {
                        userAuth = true;
                    }
                    break;
                }
            }
            return userAuth;
        }

        function getCsrf() {
            var inputElems = document.querySelectorAll('input');
            var csrfToken = '';
            var i = 0;
            for (i = 0; i < inputElems.length; i++) {
                if (inputElems[i].name === 'csrfmiddlewaretoken') {
                    csrfToken = inputElems[i].value;
                    break;
                }
            }
            return csrfToken;
        }

        function init() {
            var iconElems = document.getElementsByClassName('board-item-content-title-icon');
            var i = 0;
            for (i = 0; i < iconElems.length; i++) {
                iconElems[i].children[0].addEventListener('click', function (event) {
                    if (!getUserAuth()) {
                        var message = '<a href="/login/">Login</a> to track your applications.';
                        document.getElementById('board-header-track').innerHTML = message;
                    } else {
                        var listingId = event.target.id.substring(6);
                        var url = '/board/track/' + listingId + '/';
                        axios
                            .post(url, null, {
                                headers: {
                                    'X-CSRFToken': getCsrf(),
                                },
                            })
                            .then(function (res) {
                                if (res.status === 200) {
                                    var message = '<em>' + res.data.message + '</em> now tracked on <a href="/">your applications</a>.';
                                    document.getElementById('board-header-track').innerHTML = message;
                                }
                            })
                            .catch(function (err) {
                                console.log('Error tracking for listing id ' + listingId + '. Error: ' + err);
                                throw err;
                            });
                    }
                });
            }
        }

        init();
    </script>
{% endblock %}

main/templates/main/board_add.html
{% extends 'main/layout.html' %}

{% load static %}

{% block title %}Avocado Job Board | Job postings for the cryptoliterate companies{% endblock %}

{% block content %}
    <div class="header extended">
        <div class="header-copy small">
            <h1>
                Post a <span>job</span> for <abbr title="ETH (Ether) is the cryptocurrency token of the Ethereum platform">0.05 ETH</abbr>/mo.
            </h1>
        </div>
    </div>

    <div class="boardadd">
        <div class="boardadd-form">
            <form action="{% url 'main:board_add' %}" method="post">
                {% csrf_token %}
                <label for="id_role_title">Role Title</label>
                <input type="text" name="role_title" maxlength="50" required id="id_role_title" placeholder="Backend engineer">
                <label for="id_salary">Salary Range</label>
                <input type="text" name="salary" maxlength="40" id="id_salary" placeholder="$80k - $100k">
                <label for="id_location">Location</label>
                <input type="text" name="location" maxlength="40" required id="id_location" placeholder="London, UK">
                <label for="id_company_name">Company Name</label>
                <input type="text" name="company_name" maxlength="50" required id="id_company_name" placeholder="Avocado, Inc.">
                <label for="id_company_url">Company URL</label>
                <input type="url" name="company_url" maxlength="200" required id="id_company_url" placeholder="https://avocadojobs.com/" value="http://">
                <label for="id_tags">Tags</label>
                <input type="text" name="tags" maxlength="200" id="id_tags" placeholder="Comma separated keywords (max 3 - optional) eg. frontend, react">
                <label for="id_application_link">Application URL or Email</label>
                <input type="text" name="application_link" maxlength="200" required id="id_application_link" placeholder="https://avocadojobs.com/careers/jfd8743 OR hr@avocadojobs.com">
                <input type="submit" value="Continue to payment">
            </form>
        </div>
    </div>
{% endblock %}

main/templates/main/index.html
{% extends 'main/layout.html' %}

{% block content %}
    <div class="header">
        <div class="header-copy">
            <h1>Keep track of your job applications</h1>
        </div>
    </div>

    {% if messages %}
        <p class="alert">
            {% for message in messages %}
                {{ message }}
                <br>
            {% endfor %}
        </p>
    {% endif %}

{% endblock %}

main/templates/main/layout.html
{% load static %}
{% load app_filters %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Avocado Jobs is a job application manager and a job board for developers.">

    <link rel="dns-prefetch" href="//fonts.googleapis.com">

    <link rel="apple-touch-icon" sizes="180x180" href="{% static '/main/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static '/main/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static '/main/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static '/main/manifest.json' %}">
    <link rel="mask-icon" href="{% static '/main/safari-pinned-tab.svg' %}" color="#83bf33">
    <link rel="shortcut icon" href="{% static '/main/favicon.ico' %}">
    <meta name="msapplication-config" content="{% static '/main/browserconfig.xml' %}">
    <meta name="theme-color" content="#76a735">

    <meta property="og:title" content="Avocado Jobs">
    <meta property="og:description" content="Avocado Jobs is a job application manager and a job board for developers.">
    <meta property="og:url" content="https://avocadojobs.com">
    <meta property="og:image" content="{% static '/main/logo.png' %}">
    <meta property="og:type" content="website">

    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:creator" content="@sirodoht">
    <meta name="twitter:image" content="{% static '/main/logo.png' %}">

    <title>{% block title %}Avocado Jobs | Keep track of your job applications{% endblock %}</title>

    <link rel="stylesheet" href="{% static '/main/styles/main.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab|Source+Sans+Pro" rel="stylesheet">

    {% if not user.is_authenticated %}
        <link href="https://fonts.googleapis.com/css?family=Patrick+Hand" rel="stylesheet">
    {% endif %}
</head>
<body>

    {% if request.path == '/' %}

        {% if user.is_authenticated %}
            {% csrf_token %}
            <script src="{% static '/main/scripts/bundle-authed.js' %}"></script>
        {% else %}
            <script src="{% static '/main/scripts/bundle-nonauthed.js' %}"></script>
        {% endif %}

    {% else %}

        <div class="nav">
            <div class="nav-header">
                <a href="{% url 'main:index' %}" class="nav-header-link">
                    <img class="nav-header-link-icon" src="{% static '/main/android-chrome-192x192.png' %}" alt="logo">
                    <div class="nav-header-link-brand">Avocado Jobs</div>
                </a>
            </div>
            <div class="nav-center">
              <a href="{% url 'main:index' %}" class="nav-center-item">My applications</a>
              <div class="nav-center-separator"></div>
              <a href="{% url 'main:board' %}" class="nav-center-item {% active 'board' %}">Job Board</a><sup>beta</sup>
            </div>
            <div class="nav-links">
                {% if 'board' in request.path %}
                    <a href="{% url 'main:board_add' %}" class="nav-links-lite-nonjs">Post job listing for 0.05 ETH</a>
                {% else %}
                    <a href="/#add" class="nav-links-btn-nonjs">Add application</a>
                {% endif %}
                {% if user.is_authenticated %}
                    <a href="{% url 'main:logout' %}" class="nav-links-a-nonjs">Log out</a>
                {% else %}
                    <a href="{% url 'main:login' %}" class="nav-links-a-nonjs">Log in / Sign up</a>
                {% endif %}
            </div>
        </div>

        {% block content %}
        {% endblock %}

        <footer>
            <div class="footer-body {% if request.path == '/board/' %}large{% endif %}">
                <div class="footer-body-content">
                    <a href="{% url 'main:about' %}" title="About">About</a>
                    &nbsp;| <a href="https://medium.com/avocado-jobs" title="Blog" target="_blank" rel="noopener noreferrer">Blog</a>
                    &nbsp;| <a href="mailto:hi@avocadojobs.com" title="Say hi!" target="_blank" rel="noopener noreferrer">Email</a>
                    &nbsp;| <a href="https://twitter.com/AvocadoJobs" title="Or maybe hello?" target="_blank" rel="noopener noreferrer">Tweet</a>
                </div>
            </div>
        </footer>
    {% endif %}

</body>
</html>

main/templates/main/login.html
{% extends 'main/layout.html' %}

{% block content %}
    <div class="header">
        <div class="header-copy">
            <h1>Log in / Sign up</h1>
        </div>
    </div>

    <div class="login">
        {% if next %}
            {% if user.is_authenticated %}
                <p>
                    Your account doesn't have access to this page.
                    To proceed please login with an account that has access.
                </p>
            {% endif %}
        {% endif %}

        <p>
            Enter your email and we'll send a session link to login in fashion
            with no useless passwords.
        </p>

        <p>
            You will stay logged in until you choose to log out.
        </p>

        <form method="post" action="{% url 'main:auth' %}">
            {% csrf_token %}

            <input name="email" type="email" placeholder="Email">

            <input type="submit" value="Send link">
            <input type="hidden" name="next" value="{{ next }}">
        </form>

        {% if messages %}
            <p class="alert">
                {% for message in messages %}
                    {{ message }}
                    <br>
                {% endfor %}
            </p>
        {% endif %}

    </div>
{% endblock %}